version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  # Note: Using manual conf.py configuration for now
  # jobs:
  #   pre_build:
  #     # Generate the Sphinx configuration for this Jupyter Book so it builds.
  #     - "jupyter-book config sphinx ."

python:
   install:
   - requirements: requirements.txt

formats:
   - pdf

sphinx:
  builder: html
  fail_on_warning: true
  configuration: conf.py

