###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = "The AMPL team"
bibtex_bibfiles = ["references.bib"]
comments_config = {"hypothesis": False, "utterances": False}
copyright = "2025"
exclude_patterns = [
    "**.ipynb_checkpoints",
    "**.pytest_cache",
    ".DS_Store",
    "Thumbs.db",
    "_build",
    "tools",
]
extensions = [
    "sphinx_togglebutton",
    "sphinx_copybutton",
    "myst_nb",
    "jupyter_book",
    "sphinx_thebe",
    "sphinx_comments",
    "sphinx_external_toc",
    "sphinx.ext.intersphinx",
    "sphinx_design",
    "sphinx_book_theme",
    "sphinxcontrib.googleanalytics",
    "sphinxcontrib.bibtex",
    "sphinx_jupyterbook_latex",
    "sphinx_sitemap",
]
external_toc_exclude_missing = True
external_toc_path = "_toc.yml"
googleanalytics_id = "G-TB617QHPDG"
html_baseurl = "https://ampl.com/mo-book/"
html_favicon = "https://raw.githubusercontent.com/ampl/ampl.github.io/master/themes/static/ampl-favicon.png"
html_logo = "media/logo-03.png"
html_sourcelink_suffix = ""
html_theme = "sphinx_book_theme"
html_theme_options = {
    "search_bar_text": "Search this book...",
    "launch_buttons": {
        "notebook_interface": "classic",
        "binderhub_url": "",
        "jupyterhub_url": "",
        "thebe": False,
        "colab_url": "https://colab.research.google.com",
        "deepnote_url": "",
    },
    "path_to_docs": "",
    "repository_url": "https://github.com/ampl/amplbook.ampl.com",
    "repository_branch": "dev",
    "extra_footer": "",
    "home_page_in_toc": True,
    "announcement": "",
    "analytics": {
        "google_analytics_id": "",
        "plausible_analytics_domain": "",
        "plausible_analytics_url": "https://plausible.io/js/script.js",
    },
    "use_repository_button": True,
    "use_edit_page_button": False,
    "use_issues_button": True,
    "article_header_end": ["article-header-buttons-ampl.html"],
}
html_title = "AMPL: A Modeling Language for Mathematical Programming"
latex_engine = "pdflatex"
myst_enable_extensions = [
    "colon_fence",
    "dollarmath",
    "linkify",
    "substitution",
    "tasklist",
]
myst_url_schemes = ["mailto", "http", "https"]
nb_execution_allow_errors = False
nb_execution_cache_path = ""
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = "off"
nb_execution_timeout = 30
nb_output_stderr = "show"
numfig = True
pygments_style = "sphinx"
suppress_warnings = ["myst.domains"]
templates_path = ["_templates"]
use_jupyterbook_latex = True
use_multitoc_numbering = False
latex_elements = {
    "extraclassoptions": "oneside",  # do not leave empty pages
    "tableofcontents": "\\sphinxtableofcontents",
}
latex_documents = [
    (
        "index",
        "AMPL-Book-Python-Edition.tex",
        "AMPL: A Modeling Language for Mathematical Programming",
        "AMPL Optimization",
        "manual",
    ),
]
suppress_warnings = ["mystnb.unknown_mime_type"]
